#!/bin/bash

set -e

applebloom=games
bash_d=system
cerberus=system
cerberus_logging=system
cerberus_securetty=system
featherweight=network
gates_of_tartaros=system
got_diminished=system
libpassphrase=lib
pony_computer=system
ponyguests=system
pony_initialisation=system
pytagomacs=lib
rc_local_d=system
splashtool=multimedia

USERNAME=maandree
STTY=$(stty -g)
stty -echo
echo "[$USERNAME] Enter passphrase for AUR: "
PASSPHRASE="$(sed 1q)"
stty $STTY

cd "$(dirname "$0")"
for pkgname in "$@"; do
    (
	pkgname="$(echo $pkgname | sed s:/::g)"
	CATEGORY="$(echo $pkgname | sed y/.-/__/)"
	CATEGORY="$(eval "echo \${${CATEGORY}}")"
	cd $pkgname
	
	makepkg --install
	
	newpkg=0
	pkgver="$(. PKGBUILD && echo "${pkgver}")"
	pkgrel="$(pkgrel=1 && . PKGBUILD && echo "${pkgrel}")"
	epoch="$(epoch=0 && . PKGBUILD && echo "${epoch}")"
	install="$(install="" && . PKGBUILD && echo "${install}")"
	
	if [ ! -d .aur ]; then
	    newpkg=1
	    git clone "ssh://aur@aur4.archlinux.org/${pkgname}.git" .aur
	fi
	
	version="${pkgver}"
	if [ ! "${epoch}" = 0 ]; then
	    version="${epoch}:${version}"
	fi
	if [ ! "${pkgrel}" = 1 ]; then
	    version="${version}-${pkgrel}"
	fi
	
	cp PKGBUILD .aur
	if [ ! "${install}" = "" ]; then
	    cp "${install}" .aur
	    cd .aur
	    git add "${install}"
	    cd ..
	fi
	
	(
	    . PKGBUILD
	    cd .aur
	    for file in "${source[@]}"; do
		if [ -f ../"${file}" ]; then
		    cp ../"${file}" .
		    git add "${file}"
		fi
	    done
	    cd ..
	)
	
	cd .aur
	
	mksrcinfo
	git add PKGBUILD .SRCINFO
	
	if [ ${newpkg} = 1 ]; then
	    git commit -m "Initial import, version ${version}"
	    git push origin master
	elif [ ! "${pkgrel}" = 1 ]; then
	    git commit -m "Update package release to ${version}"
	    git push
	else
	    git commit -m "Update to ${version}"
	    git push
	fi
	
	mkaurball
	burp -u $USERNAME -p "$PASSPHRASE" -c $CATEGORY $pkgname-$pkgver-$pkgrel.src.tar.gz
    )
done

